pages = {
    "page_1": "Welcome to the Questionnaire",
    "page_2": "I am someone who is outgoing, sociable",
    "page_3": "I am someone who is compassionate, has a soft heart",
    "page_4": "I am someone who tends to be disorganized",
    "page_5": "I am someone who is relaxed, handles stress well",
    "page_6": "I am someone who has few artistic interests",
    "page_7": "I am someone who has an assertive personality",
    "page_8": "I am someone who is respectful, treats others with respect",
    "page_9": "I am someone who tends to be lazy",
    "page_10": "I am someone who stays optimistic after experiencing a setback",
    "page_11": "I am someone who is curious about many different things",
    "page_12": "I am someone who rarely feels excited or eager",
    "page_13": "I am someone who tends to find fault with others",
    "page_14": "Verbal Elaboration (1/5)",
    "page_15": "I am someone who is relaxed, handles stress well",
    "page_16": "Your time for this question has ended!",
    "page_17": "I am someone who tends to be lazy",
    "page_18": "Your time for this question has ended!",
    "page_19": "I am someone who is dependable, steady",
    "page_20": "I am someone who is moody, has up and down mood swings",
    "page_21": "I am someone who is inventive, finds clever ways to do things",
    "page_22": "I am someone who tends to be quiet",
    "page_23": "I am someone who feels little sympathy for others",
    "page_24": "I am someone who is systematic, likes to keep things in order",
    "page_25": "I am someone who can be tense",
    "page_26": "I am someone who is fascinated by art, music, or literature",
    "page_27": "I am someone who is dominant, acts as a leader",
    "page_28": "I am someone who starts arguments with others",
    "page_29": "I am someone who has difficulty getting started on tasks",
    "page_30": "I am someone who feels secure, comfortable with self",
    "page_31": "Verbal Elaboration (2/5)",
    "page_32": "I am someone who is inventive, finds clever ways to do things",
    "page_33": "Your time for this question has ended!",
    "page_34": "I am someone who is systematic, likes to keep things in order",
    "page_35": "Your time for this question has ended!",
    "page_36": "I am someone who avoids intellectual, philosophical discussions",
    "page_37": "I am someone who is less active than other people",
    "page_38": "I am someone who has a forgiving nature",
    "page_39": "I am someone who can be somewhat careless",
    "page_40": "I am someone who is emotionally stable, not easily upset",
    "page_41": "I am someone who has little creativity",
    "page_42": "I am someone who is sometimes shy, introverted",
    "page_43": "I am someone who is helpful and unselfish with others",
    "page_44": "I am someone who keeps things neat and tidy",
    "page_45": "I am someone who worries a lot",
    "page_46": "I am someone who values art and beauty",
    "page_47": "I am someone who finds it hard to influence people",
    "page_48": "Verbal Elaboration (3/5)",
    "page_49": "I am someone who has little creativity",
    "page_50": "Your time for this question has ended!",
    "page_51": "I am someone who is helpful and unselfish with others",
    "page_52": "Your time for this question has ended!",
    "page_53": "I am someone who is sometimes rude to others",
    "page_54": "I am someone who is efficient, gets things done",
    "page_55": "I am someone who often feels sad",
    "page_56": "I am someone who is complex, a deep thinker",
    "page_57": "I am someone who is full of energy",
    "page_58": "I am someone who is suspicious of others' intentions",
    "page_59": "I am someone who is reliable, can always be counted on",
    "page_60": "I am someone who keeps their emotions under control",
    "page_61": "I am someone who has difficulty imagining things",
    "page_62": "I am someone who is talkative",
    "page_63": "I am someone who can be cold and uncaring",
    "page_64": "I am someone who leaves a mess, doesn't clean up",
    "page_65": "Verbal Elaboration (4/5)",
    "page_66": "I am someone who often feels sad",
    "page_67": "Your time for this question has ended!",
    "page_68": "I am someone who is full of energy",
    "page_69": "Your time for this question has ended!",
    "page_70": "I am someone who rarely feels anxious or afraid",
    "page_71": "I am someone who thinks poetry and plays are boring",
    "page_72": "I am someone who prefers to have others take charge",
    "page_73": "I am someone who is polite, courteous to others",
    "page_74": "I am someone who is persistent, works until the task is finished",
    "page_75": "I am someone who tends to feel depressed, blue",
    "page_76": "I am someone who has little interest in abstract ideas",
    "page_77": "I am someone who shows a lot of enthusiasm",
    "page_78": "I am someone who assumes the best about people",
    "page_79": "I am someone who sometimes behaves irresponsibly",
    "page_80": "I am someone who is temperamental, gets emotional easily",
    "page_81": "I am someone who is original, comes up with new ideas",
    "page_82": "Verbal Elaboration (5/5)",
    "page_83": "I am someone who prefers to have others take charge",
    "page_84": "Your time for this question has ended!",
    "page_85": "I am someone who is polite, courteous to others",
    "page_86": "Your time for this question has ended!",
    "page_87": "You're Almost There!",
    "page_88": "Final Task",
    "page_89": "Final Task",
    "page_90": "Final Task",
    "page_91": "Final Task",
    "page_92": "Final Task",
    "page_93": "Final Task",
    "page_94": "Final Task",
    "page_95": "Final Task",
    "page_96": "Final Task",
    "page_97": "Final Task",
}
